### PR TITLE
Directly open Home Screen without logging

### PR DESCRIPTION
**Pull request by VertikaBajpai**
Issue: #117

### CODE REVIEW

**Comment by muffinboy19** [comment]
@VertikaBajpai  fix your code it have some issues

**Comment by VertikaBajpai** [comment]
@muffinboy19  May I open a new PR?

**Comment by muffinboy19** [comment]
yes

**Comment by VertikaBajpai** [comment]
Okay

**Comment by VertikaBajpai** [comment]
@muffinboy19 Issues resolved, Kindly check

**Comment by muffinboy19** [comment]
@VertikaBajpai  your code still has many errors in the main.dart file

**Comment by muffinboy19** [comment]
also where the signUpscreen() funciton is called

**Pull request closed without merging**
