### PR TITLE
Logo Added

### PR DESCRIPTION
**Pull request by akoolarni**
Issue: #2 
I have designed a logo and added it in the PR. 
Also, PFA the photo of the logo. Can be modified further based on inputs obtained from maintainers.
dona1

### CODE REVIEW

**Comment by akoolarni** [comment]
when will this be merged?

**Comment by insanecoder02** [comment]
If your logo is selected after reviewing, you will be awarded points

**Comment by akoolarni** [comment]
Seems this PR is closed.
Should I open a new PR @maintainers

**Comment by insanecoder02** [comment]
your logo is in a review phase, once the review process is done the selected logo will get awarded with points

**Comment by akoolarni** [comment]
Thanx for the clarification

**Pull request closed without merging**
