### PR TITLE
Did the assigned task

### PR DESCRIPTION
**Pull request by akoolarni**
Issue: #4 
Completed assigned work.
suggest changes if required.
Thanx

### CODE REVIEW

**Comment by muffinboy19** [comment]
hey @akoolarni  we very much appreicate your work can you pls provide us with a screen shot of your screen of this page

**Comment by muffinboy19** [comment]
you pr is merged if you do not get points , then just pin us on herer, or on the discord server

**Comment by akoolarni** [comment]
Thanx.
I haven't got points, both for login page and this task.

**Comment by akoolarni** [comment]
Yes, I have 80 points till now, excluding the points from these 2 PRs

**Pull request merged**
