### PR TITLE
Two Screen

### PR DESCRIPTION
**Pull request by rnavaneeth992**
Issue: #129 

WhatsApp Image 2023-12-21 at 08 50 39_71210daa

https://github.com/opencodeiiita/Donation-App/assets/80904345/7635146a-0494-42fa-909f-de651c430f50

WhatsApp Image 2023-12-21 at 08 50 32_e1b2c1c7

### CODE REVIEW

**Comment by muffinboy19** [comment]
you could have used diffrenet images for that ... i would suggest you add more images , and ttry to mimic the desing more ..i see at some places the design and your code is not matching @rnavaneeth992

**Comment by rnavaneeth992** [comment]
@muffinboy19 Bro I will add different images, 
Design wise for image layout (I am not sure how to do it bro it is like images are placed randomly)
I used just grid can you suggest any methods to do bro?

**Comment by muffinboy19** [comment]
Okay you add more images for now , and make a pr

**Comment by rnavaneeth992** [comment]
> Okay you add more images for now , and make a pr

Sure I will do it

**Comment by rnavaneeth992** [comment]
@muffinboy19 I didn't get points

**Comment by rnavaneeth992** [comment]
> @muffinboy19 I didn't get points

@muffinboy19 And also shall push different images sorry for this delay I got struck in another task that's why
Please check my points

**Comment by muffinboy19** [comment]
Okay we will add 30 points manually

**Comment by muffinboy19** [comment]
Message this on discord

**Comment by rnavaneeth992** [comment]
> Message this on discord

Done Bro Please check it bro

**Pull request merged**
